# autor -------------------------------------------------------------------
# carlos.perezoft@gmail.com
# 23/10/2019 21:16:08 p. m.
#
tabItem(tabName="distrib-estaciones-2DTab",
   h3("An\u00E1lisis comparativo por estaci\u00F3n para par\u00E1metros medidos durante un Mes"),
   navbarPage(tags$b("Descriptivo-2D Mensual"),
     navbarMenu("Distribuci\u00F3n Estaciones",
        tabPanel("Box Plot", icon = icon("cube"),
           helpText("An\u00E1lisis tipo Box-Plot. Compara el par\u00E1metro seleccionado para cada estaci\u00F3n."),
           bsPopover(id="boxplotEstacionesPlot", title="Box-Plot", placement = "top", trigger = "hover",
                     content=paste("Se presentan: los valores, la media y la desviaci\u00F3n est\u00E1ndar punteadas.",
                                   "Clic en el nombre de la Estaci\u00F3n para activar/desactivar su box-plot.")),
           dropdownButton(inputId = "boxplotEstacionesOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput("boxplotEstacionesParam", label = "Par\u00E1metro", width="220px",
                     choices=c("Conductividad"="MEDIA_Condu", "pH"="MEDIA_ph",
                               "Oxig. Disuelto"="MEDIA_od", "Turbiedad"="MEDIA_turb",
                               "Pot. Redox"="MEDIA_pot_redox", "Temperatura"="MEDIA_tempera"),
                     selected="MEDIA_Condu"),
              selectInput("boxplotEstacionMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                  choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                              "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                  selected = 0, multiple = TRUE),
              sliderTextInput(inputId = "boxplotEstacDiaMes", label = "D\u00EDa del Mes (T: todos)",
                   choices = c("T", seq(1:31)), grid = TRUE),
              selectInput("boxplotEstacDiaSem", label = "D\u00EDa de Semana", width="220px",
                  choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                              "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                  selected = 0, multiple = TRUE),
              awesomeCheckbox(inputId = "boxplotEstacionPtosCheck",
                          label = "Ver Puntos de Medici\u00F3n", value = FALSE, status = "success"),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
           ),
           plotlyOutput("boxplotEstacionesPlot", width = "100%", height = "500px") %>% withSpinner(type=5, color="cadetblue")
        ),
        tabPanel("Box Plot - Variaci\u00F3n Temporal-Mes", icon = icon("history"),
           helpText("An\u00E1lisis tipo Box Plot - Variaci\u00F3n Temporal-Mes. Compara el par\u00E1metro seleccionado para variaci\u00F3n temporal por mes."),
           bsPopover(id="boxplotVarTempPlot", title="Box-Plot", placement = "top", trigger = "hover",
                     content=paste("Se presentan: los valores, la media y la desviaci\u00F3n est\u00E1ndar punteadas.",
                                   "Clic en el nombre del MES para activar/desactivar su box-plot.")),
           dropdownButton(inputId = "boxplotVarTempOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput("boxplotVarTempParam", label = "Par\u00E1metro", width="220px",
                     choices=c("Conductividad"="MEDIA_Condu", "pH"="MEDIA_ph",
                               "Oxig. Disuelto"="MEDIA_od", "Turbiedad"="MEDIA_turb",
                               "Pot. Redox"="MEDIA_pot_redox", "Temperatura"="MEDIA_tempera"),
                     selected="MEDIA_Condu"),
              selectInput(inputId='boxplotVarTempEstacion', label='Estaci\u00F3n',
                  choices=c("San Miguel"="1_SAN_MIGUEL", "Anc\u00F3n Sur"="3_ANCON_SUR", "Aula Ambiental"="8_AULA_AMBIENTAL"),
                  selected = "1_SAN_MIGUEL"),
              selectInput("boxplotVarTempMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                  choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                              "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                  selected = 0, multiple = TRUE),
              sliderTextInput(inputId = "boxplotVarTempDiaMes", label = "D\u00EDa del Mes (T: todos)",
                   choices = c("T", seq(1:31)), grid = TRUE),
              selectInput("boxplotVarTempDiaSem", label = "D\u00EDa de Semana", width="220px",
                  choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                              "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                  selected = 0, multiple = TRUE),
              awesomeCheckbox(inputId = "boxplotVarTempPtosCheck",
                          label = "Ver Puntos de Medici\u00F3n", value = FALSE, status = "success"),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
           ),
           plotlyOutput("boxplotVarTempPlot", width = "100%", height = "500px") %>% withSpinner(type=7, color="cadetblue")
        ),
        tabPanel("Distribuci\u00F3n de Densidad", icon = shiny::icon("stats", lib = "glyphicon"),
           helpText("Distribuci\u00F3n de Densidad (suavizado). Compara el par\u00E1metro seleccionado para cada estaci\u00F3n."),
           dropdownButton(inputId = "densidadEstacionOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"), # Para ajutar el ancho del Select!
              selectInput("densidadEstacionesParam", label = "Par\u00E1metro", width="220px",
                     choices=c("Conductividad"="MEDIA_Condu", "pH"="MEDIA_ph",
                               "Oxig. Disuelto"="MEDIA_od", "Turbiedad"="MEDIA_turb",
                               "Pot. Redox"="MEDIA_pot_redox", "Temperatura"="MEDIA_tempera"),
                     selected="MEDIA_Condu"),
              selectInput("densidadEstacionMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                  choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                              "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                  selected = 0, multiple = TRUE),
              sliderTextInput(inputId = "densidadEstacDiaMes", label = "D\u00EDa del Mes (T: todos)",
                   choices = c("T", seq(1:31)), grid = TRUE), # Para ajutar el ancho del Select!
              selectInput("densidadEstacDiaSem", label = "D\u00EDa de Semana", width="220px",
                  choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                                         "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                  selected = 0, multiple = TRUE),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
           ),
           plotlyOutput("distriDensiEstacionesPlot", width = "100%", height = "500px") %>% withSpinner(type=4, color="cadetblue")
        ),
        tabPanel("Viol\u00EDn", icon = icon("music", lib = "glyphicon"),
           helpText("An\u00E1lisis tipo Viol\u00EDn. Compara el par\u00E1metro seleccionado para cada estaci\u00F3n."),
           bsPopover(id="violinEstacionesPlot", title="Viol\u00EDn-Plot", placement = "top", trigger = "hover",
                     content="Se presenta: Un Box-Plot enmarcado con una distribuci\u00F3n de densidad suavizada (Kernel Density)."),
           dropdownButton(inputId = "violinEstacionesOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput("violinEstacionesParam", label = "Par\u00E1metro", width="220px",
                     choices=c("Conductividad"="MEDIA_Condu", "pH"="MEDIA_ph",
                               "Oxig. Disuelto"="MEDIA_od", "Turbiedad"="MEDIA_turb",
                               "Pot. Redox"="MEDIA_pot_redox", "Temperatura"="MEDIA_tempera"),
                     selected="MEDIA_Condu"),
              selectInput("violinEstacionMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                  choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                              "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                  selected = 0, multiple = TRUE),
              sliderTextInput(inputId = "violinEstacDiaMes", label = "D\u00EDa del Mes (T: todos)",
                   choices = c("T", seq(1:31)), grid = TRUE),
              selectInput("violinEstacDiaSem", label = "D\u00EDa de Semana", width="220px",
                  choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                              "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                  selected = 0, multiple = TRUE),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
           ),
           plotlyOutput("violinEstacionesPlot", width = "100%", height = "500px") %>% withSpinner(type=5, color="cadetblue")
        )
     ),
     tabPanel("Contornos", icon = icon("paperclip"),
        helpText("An\u00E1lisis por medio de contornos (Densidad 2D)."),
        dropdownButton(inputId = "contornoEstacionesOpsBtn",
          tags$h4("Opciones de Presentaci\u00F3n:"),
          # Nota: En el listado de choices se usa una lista c("label"="id_txt"). En el server el input entrega el "id_txt".
          selectInput(inputId='contornoFiltroEstacion', label='Estaci\u00F3n',
                  choices=c("Todas"="T", "San Miguel"="1_SAN_MIGUEL", "Anc\u00F3n Sur"="3_ANCON_SUR", "Aula Ambiental"="8_AULA_AMBIENTAL"),
                  selected = "1_SAN_MIGUEL"), # Para ajutar el ancho del Select!
          selectInput("contornoEjeXEstaciones", label = "Par\u00E1metro eje X", width="220px",
                  choices=c("t sub-j"="id_t", "Conductividad"="MEDIA_Condu", "pH"="MEDIA_ph",
                            "Oxig. Disuelto"="MEDIA_od", "Turbiedad"="MEDIA_turb",
                            "Pot. Redox"="MEDIA_pot_redox", "Temperatura"="MEDIA_tempera"),
                  selected="id_t"),
          selectInput("contornoEjeYEstaciones", label = "Par\u00E1metro eje Y", width="220px",
                  choices=c("Conductividad"="MEDIA_Condu", "pH"="MEDIA_ph",
                            "Oxig. Disuelto"="MEDIA_od", "Turbiedad"="MEDIA_turb",
                            "Pot. Redox"="MEDIA_pot_redox", "Temperatura"="MEDIA_tempera"),
                  selected="MEDIA_Condu"),
          selectInput("contornoEstacionMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                  choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                              "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                  selected = 0, multiple = TRUE),
          sliderTextInput(inputId="contornoEstacDiaMes", label = "D\u00EDa del Mes (T: todos)",
                  choices = c("T", seq(1:31)), grid = TRUE),
          selectInput("contornoEstacDiaSem", label = "D\u00EDa de Semana", width="220px",
                  choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                              "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                  selected = 0, multiple = TRUE),
          selectInput(inputId='contornoEstacionMethod', label='Estilo de Representaci\u00F3n',
                  choices=c("Contorno", "Espectral", "Poligono"), selected = "Contorno"),
          awesomeCheckbox(inputId = "contornoEstacionPuntosCheck",
                          label = "Ver Puntos de Medici\u00F3n", value = FALSE, status = "success"),
          tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
          circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
          size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
        ),
        plotlyOutput("contornosEstacionesPlot", width = "100%", height = "500px") %>% withSpinner(type=4, color="cadetblue")
     ),
     navbarMenu("Correlaci\u00F3n",
        tabPanel("Correlograma", icon = icon("th-large"),
           helpText("An\u00E1lisis por medio de Correlograma."),
           dropdownButton(inputId = "correlogramaEstacionesOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput(inputId='correlogramaFiltroEstacion', label='Estaci\u00F3n',
                  choices=c("Todas"="T", "San Miguel"="1_SAN_MIGUEL", "Anc\u00F3n Sur"="3_ANCON_SUR", "Aula Ambiental"="8_AULA_AMBIENTAL"),
                  selected = "1_SAN_MIGUEL"),
              selectInput("correlogramaEstacionMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                     choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                                 "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                     selected = 0, multiple = TRUE),
              sliderTextInput(inputId="correlogramaEstacDiaMes", label = "D\u00EDa del Mes (T: todos)",
                     choices = c("T", seq(1:31)), grid = TRUE), # Para ajutar el ancho del Select!
              selectInput("correlogramaEstacDiaSem", label = "D\u00EDa de Semana", width="220px",
                     choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                                 "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                     selected = 0, multiple = TRUE),
              selectInput(inputId = 'correlogramaEstacionesMethod', label = 'Estilo de Representaci\u00F3n',
                    choices = c("C\u00EDrculo"="circle","Cuadrado"="square",
                       "Elipse"="ellipse","Num\u00E9rico"="number","Torta"="pie"),
                    selected = "circle"),
              selectInput(inputId = 'correlogramaEstacionesSection', label = 'Ver Secci\u00F3n',
                     choices = c("Completo"="full","Inferior"="lower","Superior"="upper"), selected = "upper"),
              awesomeCheckbox(inputId = "correlogramaEstacionesCoefCheck",
                          label = "Ver Coeficientes", value = FALSE, status = "success"),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
           ),
           # IMPORTANTE: corrplot genera un grafico estandar para el cual plotly no tiene WRAPPER...
           plotOutput("correlogramaEstacionesPlot", width = "100%", height = "500") %>% withSpinner(type=5, color="cadetblue")
        ),
        tabPanel("Diagrama de Cuerdas", icon = icon("life-ring"),
          h4("Diagrama de Cuerdas (visi\u00F3n circular de la correlaciones entre los par\u00E1metros)."),
          bsPopover(id="cuerdasCorrEstacionesPlotOut", title="Diagrama de Cuerdas", placement = "top", trigger = "hover",
                    content="El color rojo/verde indica una correlaci\u00F3n negativa/positiva y el ancho de la cuerda representa su magnitud."),
          dropdownButton(inputId = "cuerdasCorrEstacionesOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput(inputId='cuerdasCorrEstacionesFiltroEstacion', label='Estaci\u00F3n',
                  choices=c("Todas"="T", "San Miguel"="1_SAN_MIGUEL", "Anc\u00F3n Sur"="3_ANCON_SUR",
                          "Aula Ambiental"="8_AULA_AMBIENTAL"), selected = "1_SAN_MIGUEL"),
              selectInput("cuerdasCorrEstacionesMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                     choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                                 "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                     selected = 0, multiple = TRUE),
              sliderTextInput(inputId="cuerdasCorrEstacionesDiaMes", label = "D\u00EDa del Mes (T: todos)",
                     choices = c("T", seq(1:31)), grid = TRUE), # Para ajutar el ancho del Select!
              selectInput("cuerdasCorrEstacionesDiaSem", label = "D\u00EDa de Semana", width="220px",
                     choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                                 "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                     selected = 0, multiple = TRUE),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
          ),
          plotOutput("cuerdasCorrEstacionesPlotOut", width = "700", height = "700") %>% withSpinner(type=5, color="cadetblue"),
          helpText("[El color rojo/verde y el ancho de la cuerda indican una correlaci\u00F3n negativa/positiva y su magnitud].")
        ),
        tabPanel("Matriz de Dispersi\u00F3n",icon = icon("th"), h4("Matriz de Dispersi\u00F3n (Scatter Plot Matrix - SPLOM)"),
          bsPopover(id="splomCorrEstacionesPlotOut", title="Matriz de Dispersi\u00F3n (SPLOM)", placement = "top", trigger = "hover",
               content="Se presentan los diagramas de dispersi\u00F3n, gr\u00E1fico de densidad y valor de la correlaci\u00F3n entre par\u00E1metros."),
          dropdownButton(inputId = "splomCorrEstacionesOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput(inputId='splomCorrEstacionesFiltroEstacion', label='Estaci\u00F3n',
                  choices=c("Todas"="T", "San Miguel"="1_SAN_MIGUEL", "Anc\u00F3n Sur"="3_ANCON_SUR",
                          "Aula Ambiental"="8_AULA_AMBIENTAL"), selected = "1_SAN_MIGUEL"),
              selectInput("splomCorrEstacionesMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                     choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                                 "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                     selected = 0, multiple = TRUE),
              sliderTextInput(inputId="splomCorrEstacionesDiaMes", label = "D\u00EDa del Mes (T: todos)",
                     choices = c("T", seq(1:31)), grid = TRUE), # Para ajutar el ancho del Select!
              selectInput("splomCorrEstacionesDiaSem", label = "D\u00EDa de Semana", width="220px",
                     choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                                 "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                     selected = 0, multiple = TRUE),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
          ),
          plotlyOutput("splomCorrEstacionesPlotOut", width = "100%", height = "800") %>% withSpinner(type=4, color="cadetblue"),
          helpText("[La diagonal principal presenta la distribuci\u00F3n de desidad de cada par\u00E1metro].")
        ),
###
        tabPanel("Mapa de Calor",icon = icon("qrcode"), h4("Mapa de Calor (HEATMAP)"),
          bsPopover(id="heatmapEstacionesPlotOut", title="Mapa de Calor (HEATMAP)", placement = "top", trigger = "hover",
               content="El mapa de calor presenta las variaciones/patrones de los datos por medio de escalas de color."),
          dropdownButton(inputId = "heatmapEstacionesOpsBtn",
              tags$h4("Opciones de Presentaci\u00F3n:"),
              selectInput(inputId='heatmapEstacionesFiltroEstacion', label='Estaci\u00F3n',
                  choices=c("Todas"="T", "San Miguel"="1_SAN_MIGUEL", "Anc\u00F3n Sur"="3_ANCON_SUR",
                          "Aula Ambiental"="8_AULA_AMBIENTAL"), selected = "1_SAN_MIGUEL"),
              selectInput("heatmapEstacionesMes", label = "Mes", width="220px", # Para ajutar el ancho del Select!
                     choices = c("Enero"=1, "Febrero"=2, "Marzo"=3, "Abril"=4, "Mayo"=5, "Junio"=6,
                                 "Julio"=7, "Agosto"=8, "Septiembre"=9, "Octubre"=10, "Noviembre"=11, "Diciembre"=12),
                     selected = 0, multiple = TRUE),
              sliderTextInput(inputId="heatmapEstacionesDiaMes", label = "D\u00EDa del Mes (T: todos)",
                     choices = c("T", seq(1:31)), grid = TRUE), # Para ajutar el ancho del Select!
              selectInput("heatmapEstacionesDiaSem", label = "D\u00EDa de Semana", width="220px",
                     choices = c("Lunes"=1, "Martes"=2, "Mi\u00E9rcoles"=3,
                                 "Jueves"=4, "Viernes"=5, "S\u00E1bado"=6, "Domingo"=7),
                     selected = 0, multiple = TRUE),
              selectInput(inputId = "heatmapEstacionesTransType", label = "Aplicar transformaci\u00F3n",
                         choices = c("Ninguna", "Escalar", "Normalizar"),
                         selected = "Ninguna"),
              selectInput(inputId = 'heatmapEstacionesDendroType', label = 'Ver Dendrograma',
                         choices = c("Ninguno"='none',"Filas"='row',"Columnas"='column',"Ambos"='both'), selected = "row"),
              tags$i("Actualizaci\u00F3n autom\u00E1tica..."),
              circle = TRUE, status = "danger", icon = icon("gear"), width = "250px",
              size = "xs", tooltip = tooltipOptions(title = "Cambiar opciones...")
          ),
          plotlyOutput("heatmapEstacionesPlotOut", width = "100%", height = "1000") %>% withSpinner(type=4, color="cadetblue"),
          helpText("[Es posible agrupar de forma jer\u00E1rquica presentando un dendrograma por filas y/o columnas].")
        )
###
     )
  ) # FIN navbarPage
)
#
